# Generated by Django 3.2.3 on 2021-05-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
    ]
