# Generated by Django 3.2.3 on 2021-05-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_in_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_active',
            new_name='is_active',
        ),
    ]
